<?php

$main_smiles_array = array (          
	':-)'			=> 'smile.gif',
	':)'			=> 'smile.gif',
	'=)'			=> 'smile.gif',
	'8-)'			=> 'glass.gif',
	'8)'			=> 'glass.gif',
	':-('			=> 'sad.gif',
	';('			=> 'sad.gif',
	':('			=> 'sad.gif',
	';-)'			=> 'wink.gif',
	';)'			=> 'wink.gif',
	':-P'			=> 'tongue.gif',
	':P'			=> 'tongue.gif',
	':-D'			=> 'laugh.gif',
	'=-O'			=> 'wonder.gif',
	'*IN LOVE*'		=> 'inlove.gif',
	'%)'			=> 'eyes.gif',
	'*CRAZY*'		=> 'crazy.gif',

);

$smiles_array = array (          
	'O:-)'				=> 'angel.gif',
	'O=)'				=> 'angel.gif',
	':-['				=> 'blush.gif',
	':-*'				=> 'kiss.gif',
	':-X'				=> 'quiet.gif',
	':-x'				=> 'quiet.gif',
	'>:o'				=> 'strong.gif',
	':-|'				=> 'think.gif',
	':-\\'				=> 'pitchup.gif',
	':-/'				=> 'pitchup.gif',
	'*JOKINGLY*'		=> 'jokingly.gif',
	']:->'				=> 'devil.gif',
	'[:-}'				=> 'music.gif',
	'*KISSED*'			=> 'kissed.gif',
	'*TIRED*'			=> 'tired.gif',
	'*STOP*'			=> 'stop.gif',
	'*KISSING*'			=> 'kissing.gif',
	'*ROSE*'			=> 'rose.gif',
	'*THUMBS UP*'		=> 'thumbsup.gif',
	'*DRINK*'			=> 'drink.gif',
	'@='				=> 'bomb.gif',
	'*HELP*'			=> 'sos.gif',
	'\\m/'				=> 'macho.gif',
	'*MACHO*'			=> 'macho.gif',
	'*OK*'				=> 'ok.gif',
	'*SUP*'				=> 'wassup.gif',
	'*WASSUP*'			=> 'wassup.gif',
	'*SORRY*'			=> 'sorry.gif',
	'*BRAVO*'			=> 'bravo.gif',
	'*ROFL*'			=> 'rofl.gif',
	'*LOL*'				=> 'rofl.gif',
	'*PARDON*'			=> 'pardon.gif',
	'*NO*'				=> 'no.gif',
	'*DONT_KNOW*'		=> 'unknown.gif',
	'*UNKNOWN*'			=> 'unknown.gif',
	'*DANCE*'			=> 'dance.gif',
	'*YAHOO!*'			=> 'yahoo.gif',
	'*YAHOO*'			=> 'yahoo.gif',
	
);

?>